---
# yaml plugin used

all: 
  hosts: 
    sandboxapicdc:
    # always-on 
      ansible_host: sandboxapicdc.cisco.com
      ansible_user: admin
      #ansible_ssh_pass: ciscopsdt
      ansible_ssh_pass: "!v3G@!4@Y"
      aci_validate_certs: no
    # reserved
      # ansible_host: devnetsandbox-usw1-reservation.cisco.com:20275
      # ansible_user: cparadared
      # ansible_ssh_pass: "RETPBYXE"
      # aci_validate_certs: no
    epg_b_1:
    epg_b_2:
    epg_g_1:
    epg_g_2:
  children:
    epg:
      children:
        blue:
          hosts: 
            epg_b_[1:2]:
        green:
          hosts: 
            epg_g_[1:2]:
    apic:
      hosts:
        sandboxapicdc: